
package com.vaham.ws.orderprocessor;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-10-20T00:38:55.248-04:00
 * Generated source version: 2.7.7
 * 
 */
public final class OrderProcessorWebService_OrderProcessorWebServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://orderprocessor.ws.vaham.com/", "OrderProcessorWebServiceImplService");

    private OrderProcessorWebService_OrderProcessorWebServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = OrderProcessorWebServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        OrderProcessorWebServiceImplService ss = new OrderProcessorWebServiceImplService(wsdlURL, SERVICE_NAME);
        OrderProcessorWebService port = ss.getOrderProcessorWebServiceImplPort();  
        
        {
        System.out.println("Invoking createAccount...");
        com.vaham.ws.orderprocessor.Account _createAccount_account = new com.vaham.ws.orderprocessor.Account();
        com.vaham.ws.orderprocessor.Address _createAccount_accountAddress = new com.vaham.ws.orderprocessor.Address();
        _createAccount_accountAddress.setAddrID(9151245946521980138l);
        _createAccount_accountAddress.setCountry("Country1067864195");
        _createAccount_accountAddress.setDetails("Details685249171");
        _createAccount_accountAddress.setPhone("Phone759426373");
        _createAccount_accountAddress.setPostalCode("PostalCode-1155034511");
        _createAccount_accountAddress.setProvince("Province394887597");
        _createAccount_account.setAddress(_createAccount_accountAddress);
        _createAccount_account.setEmail("Email787685522");
        _createAccount_account.setFirstName("FirstName364451122");
        _createAccount_account.setLastName("LastName299927416");
        _createAccount_account.setPassword("Password1537148668");
        _createAccount_account.setUsername("Username-62928476");
        boolean _createAccount__return = port.createAccount(_createAccount_account);
        System.out.println("createAccount.result=" + _createAccount__return);


        }
        {
        System.out.println("Invoking confirmOrder...");
        com.vaham.ws.orderprocessor.PurchaseOrder _confirmOrder_shoppingCart = new com.vaham.ws.orderprocessor.PurchaseOrder();
        _confirmOrder_shoppingCart.setCdIdListString("CdIdListString742008892");
        _confirmOrder_shoppingCart.setErrorString("ErrorString-1013748694");
        _confirmOrder_shoppingCart.setPurchaseOrderID(-593962881968718677l);
        com.vaham.ws.orderprocessor.Address _confirmOrder_shoppingCartShippingAddress = new com.vaham.ws.orderprocessor.Address();
        _confirmOrder_shoppingCartShippingAddress.setAddrID(-2600164448763359391l);
        _confirmOrder_shoppingCartShippingAddress.setCountry("Country-948913332");
        _confirmOrder_shoppingCartShippingAddress.setDetails("Details-588372443");
        _confirmOrder_shoppingCartShippingAddress.setPhone("Phone942195707");
        _confirmOrder_shoppingCartShippingAddress.setPostalCode("PostalCode-728244335");
        _confirmOrder_shoppingCartShippingAddress.setProvince("Province-116224896");
        _confirmOrder_shoppingCart.setShippingAddress(_confirmOrder_shoppingCartShippingAddress);
        _confirmOrder_shoppingCart.setTotalPrice(0.6676868025285364);
        _confirmOrder_shoppingCart.setUsername("Username-1363597853");
        com.vaham.ws.orderprocessor.PaymentInfo _confirmOrder_paymentInfo = new com.vaham.ws.orderprocessor.PaymentInfo();
        _confirmOrder_paymentInfo.setPaymentIDNumber("PaymentIDNumber-1068956249");
        _confirmOrder_paymentInfo.setPaymentStatus("PaymentStatus40032209");
        _confirmOrder_paymentInfo.setPaymentType("PaymentType-1869532688");
        com.vaham.ws.orderprocessor.PurchaseOrder _confirmOrder__return = port.confirmOrder(_confirmOrder_shoppingCart, _confirmOrder_paymentInfo);
        System.out.println("confirmOrder.result=" + _confirmOrder__return);


        }
        {
        System.out.println("Invoking createOrder...");
        com.vaham.ws.orderprocessor.PurchaseOrder _createOrder_purchaseOrder = new com.vaham.ws.orderprocessor.PurchaseOrder();
        _createOrder_purchaseOrder.setCdIdListString("CdIdListString656232356");
        _createOrder_purchaseOrder.setErrorString("ErrorString524121412");
        _createOrder_purchaseOrder.setPurchaseOrderID(3026445269583383053l);
        com.vaham.ws.orderprocessor.Address _createOrder_purchaseOrderShippingAddress = new com.vaham.ws.orderprocessor.Address();
        _createOrder_purchaseOrderShippingAddress.setAddrID(4001494308995118355l);
        _createOrder_purchaseOrderShippingAddress.setCountry("Country-2128322905");
        _createOrder_purchaseOrderShippingAddress.setDetails("Details-1498896261");
        _createOrder_purchaseOrderShippingAddress.setPhone("Phone-914738358");
        _createOrder_purchaseOrderShippingAddress.setPostalCode("PostalCode1106354198");
        _createOrder_purchaseOrderShippingAddress.setProvince("Province-1646518213");
        _createOrder_purchaseOrder.setShippingAddress(_createOrder_purchaseOrderShippingAddress);
        _createOrder_purchaseOrder.setTotalPrice(0.08467485431069854);
        _createOrder_purchaseOrder.setUsername("Username-1661839891");
        com.vaham.ws.orderprocessor.PurchaseOrder _createOrder__return = port.createOrder(_createOrder_purchaseOrder);
        System.out.println("createOrder.result=" + _createOrder__return);


        }
        {
        System.out.println("Invoking getAccount...");
        java.lang.String _getAccount_username = "_getAccount_username2093502314";
        java.lang.String _getAccount_password = "_getAccount_password-26718864";
        com.vaham.ws.orderprocessor.Account _getAccount__return = port.getAccount(_getAccount_username, _getAccount_password);
        System.out.println("getAccount.result=" + _getAccount__return);


        }

        System.exit(0);
    }

}
