package com.vaham.ws.orderprocessor;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-10-20T00:38:55.320-04:00
 * Generated source version: 2.7.7
 * 
 */
@WebServiceClient(name = "OrderProcessorWebServiceImplService", 
                  wsdlLocation = "http://localhost:8080/MusicZoneBackend/OrderProcessorWebService?wsdl",
                  targetNamespace = "http://orderprocessor.ws.vaham.com/") 
public class OrderProcessorWebServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://orderprocessor.ws.vaham.com/", "OrderProcessorWebServiceImplService");
    public final static QName OrderProcessorWebServiceImplPort = new QName("http://orderprocessor.ws.vaham.com/", "OrderProcessorWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/MusicZoneBackend/OrderProcessorWebService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OrderProcessorWebServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/MusicZoneBackend/OrderProcessorWebService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OrderProcessorWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OrderProcessorWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderProcessorWebServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OrderProcessorWebServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OrderProcessorWebServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OrderProcessorWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns OrderProcessorWebService
     */
    @WebEndpoint(name = "OrderProcessorWebServiceImplPort")
    public OrderProcessorWebService getOrderProcessorWebServiceImplPort() {
        return super.getPort(OrderProcessorWebServiceImplPort, OrderProcessorWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderProcessorWebService
     */
    @WebEndpoint(name = "OrderProcessorWebServiceImplPort")
    public OrderProcessorWebService getOrderProcessorWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(OrderProcessorWebServiceImplPort, OrderProcessorWebService.class, features);
    }

}
