
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.vaham.ws.productcatalog;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-10-20T00:39:07.898-04:00
 * Generated source version: 2.7.7
 * 
 */

@javax.jws.WebService(
                      serviceName = "ProductCatalogWSImplService",
                      portName = "ProductCatalogWSImplPort",
                      targetNamespace = "http://productcatalog.ws.vaham.com/",
                      wsdlLocation = "http://localhost:8080/MusicZoneBackend/ProductCatalogWebService?wsdl",
                      endpointInterface = "com.vaham.ws.productcatalog.ProductCatalogWS")
                      
public class ProductCatalogWSImpl implements ProductCatalogWS {

    private static final Logger LOG = Logger.getLogger(ProductCatalogWSImpl.class.getName());

    /* (non-Javadoc)
     * @see com.vaham.ws.productcatalog.ProductCatalogWS#getCategoryList(*
     */
    public com.vaham.ws.productcatalog.CategoryList getCategoryList() { 
        LOG.info("Executing operation getCategoryList");
        try {
            com.vaham.ws.productcatalog.CategoryList _return = new com.vaham.ws.productcatalog.CategoryList();
            java.util.List<java.lang.String> _returnCategoryList = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnCategoryListVal1 = "_returnCategoryListVal-2068969856";
            _returnCategoryList.add(_returnCategoryListVal1);
            _return.getCategoryList().addAll(_returnCategoryList);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vaham.ws.productcatalog.ProductCatalogWS#getProductList(java.lang.String  categoryId )*
     */
    public com.vaham.ws.productcatalog.ProductList getProductList(java.lang.String categoryId) { 
        LOG.info("Executing operation getProductList");
        System.out.println(categoryId);
        try {
            com.vaham.ws.productcatalog.ProductList _return = new com.vaham.ws.productcatalog.ProductList();
            java.util.List<com.vaham.ws.productcatalog.ProductInfo> _returnProductList = new java.util.ArrayList<com.vaham.ws.productcatalog.ProductInfo>();
            com.vaham.ws.productcatalog.ProductInfo _returnProductListVal1 = new com.vaham.ws.productcatalog.ProductInfo();
            _returnProductListVal1.setCdId("CdId-556039558");
            _returnProductListVal1.setTitle("Title9720989");
            _returnProductList.add(_returnProductListVal1);
            _return.getProductList().addAll(_returnProductList);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vaham.ws.productcatalog.ProductCatalogWS#getProductInfo(java.lang.String  productId )*
     */
    public com.vaham.ws.productcatalog.Cd getProductInfo(java.lang.String productId) { 
        LOG.info("Executing operation getProductInfo");
        System.out.println(productId);
        try {
            com.vaham.ws.productcatalog.Cd _return = new com.vaham.ws.productcatalog.Cd();
            _return.setCategory("Category-473682389");
            _return.setCdId("CdId-1896056655");
            _return.setPrice(Long.valueOf(-455278434102655276l));
            _return.setTitle("Title-789371002");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
