package com.vaham.ws.productcatalog;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-10-20T00:39:07.915-04:00
 * Generated source version: 2.7.7
 * 
 */
@WebServiceClient(name = "ProductCatalogWSImplService", 
                  wsdlLocation = "http://localhost:8080/MusicZoneBackend/ProductCatalogWebService?wsdl",
                  targetNamespace = "http://productcatalog.ws.vaham.com/") 
public class ProductCatalogWSImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://productcatalog.ws.vaham.com/", "ProductCatalogWSImplService");
    public final static QName ProductCatalogWSImplPort = new QName("http://productcatalog.ws.vaham.com/", "ProductCatalogWSImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/MusicZoneBackend/ProductCatalogWebService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ProductCatalogWSImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/MusicZoneBackend/ProductCatalogWebService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ProductCatalogWSImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ProductCatalogWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductCatalogWSImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ProductCatalogWSImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ProductCatalogWSImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ProductCatalogWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ProductCatalogWS
     */
    @WebEndpoint(name = "ProductCatalogWSImplPort")
    public ProductCatalogWS getProductCatalogWSImplPort() {
        return super.getPort(ProductCatalogWSImplPort, ProductCatalogWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductCatalogWS
     */
    @WebEndpoint(name = "ProductCatalogWSImplPort")
    public ProductCatalogWS getProductCatalogWSImplPort(WebServiceFeature... features) {
        return super.getPort(ProductCatalogWSImplPort, ProductCatalogWS.class, features);
    }

}
