
package com.vaham.ws.productcatalog;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-10-20T00:39:07.852-04:00
 * Generated source version: 2.7.7
 * 
 */
public final class ProductCatalogWS_ProductCatalogWSImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://productcatalog.ws.vaham.com/", "ProductCatalogWSImplService");

    private ProductCatalogWS_ProductCatalogWSImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ProductCatalogWSImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ProductCatalogWSImplService ss = new ProductCatalogWSImplService(wsdlURL, SERVICE_NAME);
        ProductCatalogWS port = ss.getProductCatalogWSImplPort();  
        
        {
        System.out.println("Invoking getCategoryList...");
        com.vaham.ws.productcatalog.CategoryList _getCategoryList__return = port.getCategoryList();
        System.out.println("getCategoryList.result=" + _getCategoryList__return);


        }
        {
        System.out.println("Invoking getProductList...");
        java.lang.String _getProductList_categoryId = "_getProductList_categoryId-1151262694";
        com.vaham.ws.productcatalog.ProductList _getProductList__return = port.getProductList(_getProductList_categoryId);
        System.out.println("getProductList.result=" + _getProductList__return);


        }
        {
        System.out.println("Invoking getProductInfo...");
        java.lang.String _getProductInfo_productId = "_getProductInfo_productId2079038042";
        com.vaham.ws.productcatalog.Cd _getProductInfo__return = port.getProductInfo(_getProductInfo_productId);
        System.out.println("getProductInfo.result=" + _getProductInfo__return);


        }

        System.exit(0);
    }

}
