package com.vaham.ws.productcatalog;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-10-20T00:39:07.909-04:00
 * Generated source version: 2.7.7
 * 
 */
@WebService(targetNamespace = "http://productcatalog.ws.vaham.com/", name = "ProductCatalogWS")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ProductCatalogWS {

    @WebResult(name = "return", targetNamespace = "http://productcatalog.ws.vaham.com/", partName = "return")
    @Action(input = "http://productcatalog.ws.vaham.com/ProductCatalogWS/getCategoryListRequest", output = "http://productcatalog.ws.vaham.com/ProductCatalogWS/getCategoryListResponse")
    @WebMethod
    public CategoryList getCategoryList();

    @WebResult(name = "return", targetNamespace = "http://productcatalog.ws.vaham.com/", partName = "return")
    @Action(input = "http://productcatalog.ws.vaham.com/ProductCatalogWS/getProductListRequest", output = "http://productcatalog.ws.vaham.com/ProductCatalogWS/getProductListResponse")
    @WebMethod
    public ProductList getProductList(
        @WebParam(partName = "categoryId", name = "categoryId")
        java.lang.String categoryId
    );

    @WebResult(name = "return", targetNamespace = "http://productcatalog.ws.vaham.com/", partName = "return")
    @Action(input = "http://productcatalog.ws.vaham.com/ProductCatalogWS/getProductInfoRequest", output = "http://productcatalog.ws.vaham.com/ProductCatalogWS/getProductInfoResponse")
    @WebMethod
    public Cd getProductInfo(
        @WebParam(partName = "productId", name = "productId")
        java.lang.String productId
    );
}
